#pragma once

#define LUCI_MOUSE_BUTTON_1			0
#define LUCI_MOUSE_BUTTON_2			1
#define LUCI_MOUSE_BUTTON_3			2
#define LUCI_MOUSE_BUTTON_4			3
#define LUCI_MOUSE_BUTTON_5			4
#define LUCI_MOUSE_BUTTON_6			5
#define LUCI_MOUSE_BUTTON_7			6
#define LUCI_MOUSE_BUTTON_8			7
#define LUCI_MOUSE_BUTTON_LEFT		LUCI_MOUSE_BUTTON_1
#define LUCI_MOUSE_BUTTON_RIGHT		LUCI_MOUSE_BUTTON_2
#define LUCI_MOUSE_BUTTON_MIDDLE	LUCI_MOUSE_BUTTON_3
#define LUCI_MOUSE_BUTTON_LAST		LUCI_MOUSE_BUTTON_8
