name: C++ Make

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: generate
      run: |
        chmod +x ./scripts/Linux-GenerateMakefiles.sh
        ./scripts/Linux-GenerateMakefiles.sh
    - name: make
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
